baseURL = "https://awilliams.github.io/"
languageCode = "en-us"
title = "awilliams"
staticDir = ["cv", "static"]

theme = "etch"
pygmentsCodeFences = true  # enable GitHub style code snippets
[params]
  highlight = true
