baseURL = "https://awilliams.github.io/"
languageCode = "en-us"
title = "awilliams:dev"
staticDir = ["cv"]

theme = "etch"
pygmentsCodeFences = true  # enable GitHub style code snippets
[params]
  highlight = true
